[build]
# Crea el entorno virtual y luego instala el paquete en modo editable
installCommand = "python -m venv --copies /opt/venv && . /opt/venv/bin/activate && python -m pip install -e ."

[run]
# Activa el entorno virtual y ejecuta el comando entry point 'chatbot'
runCommand = "bash -c 'source /opt/venv/bin/activate && chatbot'"
